.job_template: &cargo_build
  stage: build
  script:
    - rustc --version
    - cargo check

variables:
  RUSTC_STABLE_VERSION: "1.35"

stages:
  - build
  - test
  - lint
  - deploy

Rustc Stable:
  <<: *cargo_build
  image: library/rust:$RUSTC_STABLE_VERSION

Rustc Nightly:
  <<: *cargo_build
  image: rustlang/rust:nightly

Linting:
  image: library/rust:$RUSTC_STABLE_VERSION
  stage: lint
  before_script:
    - rustup component add clippy-preview
  script:
    - cargo clippy -- -D warnings
  allow_failure: true

Integration tests:
  image: library/rust:$RUSTC_STABLE_VERSION
  variables:
    EVENTSTORE_HOST: "eventstore"
  services:
    - name: eventstore/eventstore:release-4.1.0
      alias: eventstore
  script:
    - rustc --version
    - cargo test

push on crates.io:
  stage: deploy
  image: library/rust:$RUSTC_STABLE_VERSION
  only:
    - tags

  script:
    - cargo --version
    - cargo login $CRATE_TOKEN
    - cargo package
    - cargo publish

